### ISSUE TITLE
не работает плагин

### ISSUE THREAD

**Issue by vissmu** [feymerwtf/fmSubscribe#1]
постоянно выдает каждые 3 секунды такие ошибки
[17:24:32 WARN]: [fmSubscribe] Plugin fmSubscribe v1.14 generated an exception while executing task 16
java.lang.NoClassDefFoundError: net/milkbowl/vault/chat/Chat
        at fmSubscribe-1.14.jar/ru.feymer.fmsubscribe.tasks.UpdatePrefix.setupChat(UpdatePrefix.java:55) ~[fmSubscribe-1.14.jar:?]
        at fmSubscribe-1.14.jar/ru.feymer.fmsubscribe.tasks.UpdatePrefix.run(UpdatePrefix.java:17) ~[fmSubscribe-1.14.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.1.jar:1.21.1-DEV-a3e3e98]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.21.1.jar:1.21.1-DEV-a3e3e98]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.chat.Chat
        ... 8 more
[17:24:35 WARN]: [fmSubscribe] Plugin fmSubscribe v1.14 generated an exception while executing task 16
java.lang.NoClassDefFoundError: net/milkbowl/vault/chat/Chat
        at fmSubscribe-1.14.jar/ru.feymer.fmsubscribe.tasks.UpdatePrefix.setupChat(UpdatePrefix.java:55) ~[fmSubscribe-1.14.jar:?]
        at fmSubscribe-1.14.jar/ru.feymer.fmsubscribe.tasks.UpdatePrefix.run(UpdatePrefix.java:17) ~[fmSubscribe-1.14.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.1.jar:1.21.1-DEV-a3e3e98]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.21.1.jar:1.21.1-DEV-a3e3e98]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.chat.Chat
        ... 8 more
[17:24:35 WARN]: [fmSubscribe] Plugin fmSubscribe v1.14 generated an exception while executing task 15
java.lang.NoClassDefFoundError: net/milkbowl/vault/chat/Chat
        at fmSubscribe-1.14.jar/ru.feymer.fmsubscribe.tasks.Clear.setupChat(Clear.java:50) ~[fmSubscribe-1.14.jar:?]
        at fmSubscribe-1.14.jar/ru.feymer.fmsubscribe.tasks.Clear.run(Clear.java:19) ~[fmSubscribe-1.14.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.1.jar:1.21.1-DEV-a3e3e98]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.21.1.jar:1.21.1-DEV-a3e3e98]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.chat.Chat

**Comment by malok6666** [comment]
Hello! I have the same situation with messages being displayed every 2-3 seconds. Did you manage to solve this problem?

![Image](https://github.com/user-attachments/assets/43c94362-fb2e-4f3d-abe6-6676df125172)

**Comment by SergeySpy** [comment]
У плагина есть пара недочётов.
Первый, проверка обновлений не работает, из-за неё как раз в консоле сервера появляется куча ошибок.
Второй, работа с префиксами, Vault обязательно должен быть установлен на сервере, во-вторых у игрока должен быть какой-то префикс, что бы этот плагин его отредактировал, без этого он будет выдавать ошибку.
Собственно я для своего сервера подкорректировал код, убрал проверку на обновления и вместо редактирования префикса поставил добавление к имеющемуся префиксу переменной из конфиг файла.
Если вам нужно, могу скинуть вам свою версию.
___

The plugin has a couple of shortcomings.
First, the update check does not work, because of it, a bunch of errors appear in the server console.
Second, working with prefixes, Vault must be installed on the server, secondly, the player must have some prefix for this plugin to edit it, without this it will give an error.
Actually, I corrected the code for my server, removed the update check and instead of editing the prefix, I added a variable from the config file to the existing prefix.
If you need, I can send you my version.

**Comment by malok6666** [comment]
"... Если нужно, могу скинуть вам свою версию."

Здравствуйте! Был бы очень Вам признателен за Вашу версию. Сэкономите мне время на редактировании.

**Comment by SergeySpy** [comment]
> Здравствуйте! Был бы очень Вам признателен за Вашу версию. Сэкономите мне время на редактировании.

Пиши где тебе скинуть или куда отправить?

**Comment by malok6666** [comment]
> > Здравствуйте! Буду очень признателен за вашу версию. Это сэкономит мне время на редактировании.
> 
> Напиши, куда тебе скинуть или отправить?

Приветствую! Думаю можно просто выложить на любой файлообменник, а кому надо - скачают.

**Comment by SergeySpy** [comment]
> Приветствую! Думаю можно просто выложить на любой файлообменник, а кому надо - скачают.

https://drive.google.com/file/d/1ZaejZDaFQ3lwc2nwHeSjyXY_N3yZMVqA/view?usp=sharing
